export type Service = {
  id: string;
  slug: string;
  name: string;
  logo: string;
  description: string;
  problems: string[];
};

const logo = (domain: string) => `https://logo.clearbit.com/${domain}`;

export const services: Service[] = [
  {
    id: "776f18a7-4f8b-4183-8f70-59c21f861616",
    slug: "linkedin",
    name: "LinkedIn",
    logo: logo("linkedin.com"),
    description: "Professional networking and job search platform.",
    problems: ["Feed not loading", "Can't send messages", "Login issues", "Job search broken"],
  },
  {
    id: "513fbf5d-7113-480d-8027-a9cdaf4f0de5",
    slug: "linktree",
    name: "Linktree",
    logo: logo("linktr.ee"),
    description: "Link-in-bio landing page tool for creators.",
    problems: ["Page not loading", "Links redirect incorrectly", "Editor not saving"],
  },
  {
    id: "ce53f987-ff35-4bde-872e-7c11a2c5934f",
    slug: "blink-charging",
    name: "Blink Charging",
    logo: logo("blinkcharging.com"),
    description: "Electric vehicle charging network and equipment.",
    problems: ["Charger offline", "App can't start session", "Payment declined"],
  },
  {
    id: "7c1a8e65-9a80-41f2-bdd7-94a2c35318f0",
    slug: "spotify",
    name: "Spotify",
    logo: logo("spotify.com"),
    description: "Music and podcast streaming service.",
    problems: ["Songs won't play", "App keeps crashing", "Search not working", "Offline downloads missing"],
  },
  {
    id: "113becea-c489-4774-952e-57037eb14096",
    slug: "youtube",
    name: "YouTube",
    logo: logo("youtube.com"),
    description: "Video sharing and streaming platform.",
    problems: ["Videos buffering", "Comments not loading", "Upload stuck", "Playback error"],
  },
  {
    id: "bb57ceb3-e405-4ef7-979c-e480b9613ca1",
    slug: "call-of-duty",
    name: "Call of Duty",
    logo: logo("callofduty.com"),
    description: "Online multiplayer first-person shooter franchise.",
    problems: ["Can't connect to servers", "Matchmaking stuck", "High ping / lag", "Game crashes on launch"],
  },
  {
    id: "3c7f15b7-43f0-4ec1-93cd-89718c723b07",
    slug: "x-twitter",
    name: "X (Twitter)",
    logo: logo("x.com"),
    description: "Social media platform for short posts and news.",
    problems: ["Timeline not refreshing", "Can't post", "DMs not sending", "Media won't load"],
  },
  {
    id: "47cefbc6-6edd-4be3-b557-4c3b3b2b1b0d",
    slug: "claude-ai",
    name: "Claude AI",
    logo: logo("claude.ai"),
    description: "AI assistant by Anthropic for chat and coding.",
    problems: ["Responses not loading", "Capacity constraints", "Login issues", "API errors"],
  },
  {
    id: "2960fe3c-67af-4f4a-a509-e123804f5bd0",
    slug: "optimum-cablevision",
    name: "Optimum / Cablevision",
    logo: logo("optimum.com"),
    description: "Cable TV, internet, and phone provider.",
    problems: ["Internet outage", "Slow speeds", "TV signal lost", "Router not connecting"],
  },
  {
    id: "d2a82784-d37d-4bc3-aa31-8420c00def97",
    slug: "usps",
    name: "USPS",
    logo: logo("usps.com"),
    description: "United States Postal Service mail and package delivery.",
    problems: ["Tracking not updating", "Website down", "Package delayed", "Can't schedule pickup"],
  },
  {
    id: "eb1e98d7-7f56-459f-9f24-495d3d369af7",
    slug: "samsung",
    name: "Samsung",
    logo: logo("samsung.com"),
    description: "Electronics maker: phones, TVs, and appliances.",
    problems: ["SmartThings not responding", "Account login issues", "Software update failing"],
  },
  {
    id: "0c0bc7f7-32f3-4820-ad7b-c94713c3f2c2",
    slug: "steam",
    name: "Steam",
    logo: logo("steampowered.com"),
    description: "PC gaming store, library, and community.",
    problems: ["Store not loading", "Downloads stuck", "Friends list offline", "Can't launch games"],
  },
  {
    id: "acdf04c2-dc81-43d6-81cf-5960e2deeecc",
    slug: "discord",
    name: "Discord",
    logo: logo("discord.com"),
    description: "Voice, video, and text chat for communities.",
    problems: ["Messages not sending", "Voice chat cutting out", "Can't connect", "Server outage"],
  },
  {
    id: "5676993f-bffd-4b9f-a237-9509bed1e377",
    slug: "netflix",
    name: "Netflix",
    logo: logo("netflix.com"),
    description: "Subscription video streaming service.",
    problems: ["Playback error", "App won't open", "Buffering constantly", "Login issues"],
  },
  {
    id: "46305af1-d3ac-4250-9d2a-022e1ad345cb",
    slug: "instagram",
    name: "Instagram",
    logo: logo("instagram.com"),
    description: "Photo and video sharing social network.",
    problems: ["Feed not loading", "Stories won't post", "DMs broken", "Account locked out"],
  },
  {
    id: "1f789024-55cd-4444-9c17-b7bde47f58c2",
    slug: "facebook",
    name: "Facebook",
    logo: logo("facebook.com"),
    description: "Social networking platform by Meta.",
    problems: ["News feed blank", "Can't log in", "Messenger not connecting", "Pages not loading"],
  },
  {
    id: "e7c09635-2b47-4d7e-b2e0-0b1c9da835a1",
    slug: "whatsapp",
    name: "WhatsApp",
    logo: logo("whatsapp.com"),
    description: "Encrypted messaging and calling app.",
    problems: ["Messages not delivering", "Calls dropping", "Stuck on connecting", "Backup failing"],
  },
  {
    id: "22ea7574-685c-46ac-bbf1-9bdfea6f0f14",
    slug: "gmail",
    name: "Gmail",
    logo: logo("gmail.com"),
    description: "Google's email service.",
    problems: ["Emails not arriving", "Can't send mail", "Attachment errors", "Login loop"],
  },
  {
    id: "3546e35d-3135-48d7-996d-6f8e408f6ce8",
    slug: "google",
    name: "Google",
    logo: logo("google.com"),
    description: "Search engine and web services.",
    problems: ["Search not loading", "Drive unavailable", "Maps not responding", "Account sign-in issues"],
  },
  {
    id: "56b5a8d3-de12-4cd0-b605-bcfbffc79133",
    slug: "amazon",
    name: "Amazon",
    logo: logo("amazon.com"),
    description: "Online retail and cloud services giant.",
    problems: ["Website down", "Checkout failing", "Orders not updating", "Prime Video buffering"],
  },
  {
    id: "bc803c20-f690-42c3-969e-f8d344372453",
    slug: "paypal",
    name: "PayPal",
    logo: logo("paypal.com"),
    description: "Online payments and money transfers.",
    problems: ["Payment not going through", "Can't log in", "Transfer delayed", "App error"],
  },
  {
    id: "3436313e-0fc4-43b7-9ae2-0aea3989b18b",
    slug: "reddit",
    name: "Reddit",
    logo: logo("reddit.com"),
    description: "Community forums and discussion boards.",
    problems: ["Feed won't load", "Comments missing", "Can't post", "App crashing"],
  },
  {
    id: "604042e4-3f73-4774-8c27-bb737f6b3ddf",
    slug: "tiktok",
    name: "TikTok",
    logo: logo("tiktok.com"),
    description: "Short-form video sharing platform.",
    problems: ["Videos not loading", "Upload stuck", "For You page frozen", "Login issues"],
  },
  {
    id: "1331015e-9508-4d0b-b292-570734c0f5d6",
    slug: "twitch",
    name: "Twitch",
    logo: logo("twitch.tv"),
    description: "Live streaming platform for gaming and more.",
    problems: ["Streams buffering", "Chat not connecting", "Can't go live", "VODs unavailable"],
  },
  {
    id: "47688b3d-2f88-4c5a-97a5-0b0d2782b870",
    slug: "zoom",
    name: "Zoom",
    logo: logo("zoom.us"),
    description: "Video conferencing and online meetings.",
    problems: ["Can't join meeting", "Audio cutting out", "Video freezing", "Login errors"],
  },
  {
    id: "05808715-cffc-4ccd-8e68-51b4d201f679",
    slug: "github",
    name: "GitHub",
    logo: logo("github.com"),
    description: "Code hosting and collaboration platform.",
    problems: ["Git push failing", "Actions not running", "Pages down", "API errors"],
  },
  {
    id: "3c76f759-6225-4541-a94c-57c77a670d51",
    slug: "cloudflare",
    name: "Cloudflare",
    logo: logo("cloudflare.com"),
    description: "CDN, DNS, and web security provider.",
    problems: ["522 connection timed out", "DNS not resolving", "Dashboard down", "Widespread site outages"],
  },
  {
    id: "93d487dc-c3b8-4a43-9028-6b8f66b2d62b",
    slug: "verizon",
    name: "Verizon",
    logo: logo("verizon.com"),
    description: "Mobile carrier and internet provider.",
    problems: ["No signal", "Mobile data not working", "Calls dropping", "SOS mode stuck"],
  },
  {
    id: "e281295b-2581-44ed-8930-2c3c6787af65",
    slug: "att",
    name: "AT&T",
    logo: logo("att.com"),
    description: "Telecommunications and wireless carrier.",
    problems: ["Network outage", "Slow data speeds", "Text messages failing", "Fiber internet down"],
  },
  {
    id: "a7667dda-f874-4d58-8f5d-d49e6ec335f0",
    slug: "roblox",
    name: "Roblox",
    logo: logo("roblox.com"),
    description: "Online game platform and creation system.",
    problems: ["Can't join games", "Error code 277", "Avatar not loading", "Purchases failing"],
  },
];
